spring:
  application:
    name: auth-service
  config:
    activate:
      on-profile: local
    import:
      - security/application-cors.yml
      - security/application-database.yml
      - security/application-auth.yml
      - security/application-oauth.yml

eureka:
  instance:
    instance-id: 127.0.0.1
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/